#undef ND_TREE_EMULATOR_TYPE
#undef ND_TREE_EMULATOR_NAME_SETUP
#undef ND_TREE_EMULATOR_NAME_INTERPOLATE
#undef ND_TREE_EMULATOR_NAME_INTERPOLATE_SINGLE
#undef ND_TREE_EMULATOR_NAME_INTERPOLATE_SINGLE_DX1
#undef ND_TREE_EMULATOR_NAME_FREE
<<<<<<< HEAD
#define ND_TREE_EMULATOR_TYPE unsigned char, unsigned char, 1, 3, 1, 14
#define ND_TREE_EMULATOR_NAME_SETUP test1_sparse_best_emulator_setup
#define ND_TREE_EMULATOR_NAME_INTERPOLATE test1_sparse_best_emulator_interpolate
#define ND_TREE_EMULATOR_NAME_FREE test1_sparse_best_emulator_free
=======
#define ND_TREE_EMULATOR_TYPE unsigned long, 1, 3, 8569665, 8388608
#define ND_TREE_EMULATOR_NAME_SETUP sro_logenergy_max_err_emulator_setup
#define ND_TREE_EMULATOR_NAME_INTERPOLATE sro_logenergy_max_err_emulator_interpolate
#define ND_TREE_EMULATOR_NAME_INTERPOLATE_SINGLE sro_logenergy_max_err_emulator_interpolate_single
#define ND_TREE_EMULATOR_NAME_INTERPOLATE_SINGLE_DX1 sro_logenergy_max_err_emulator_interpolate_single_dx1
#define ND_TREE_EMULATOR_NAME_FREE sro_logenergy_max_err_emulator_free
>>>>>>> memory_optimizations
