#undef ND_TREE_EMULATOR_TYPE
#undef ND_TREE_EMULATOR_NAME_SETUP
#undef ND_TREE_EMULATOR_NAME_INTERPOLATE
#undef ND_TREE_EMULATOR_NAME_FREE
#define ND_TREE_EMULATOR_TYPE unsigned long, 1, 3, 2555297, 8388608
#define ND_TREE_EMULATOR_NAME_SETUP test_v2_sparse_emulator_setup
#define ND_TREE_EMULATOR_NAME_INTERPOLATE test_v2_sparse_emulator_interpolate
#define ND_TREE_EMULATOR_NAME_FREE test_v2_sparse_emulator_free
